title: Amanatullah Pandu Zenklinov
description: Data Scientist & Lecturer
site_title: '@zenklinov - Amanatullah Pandu Zenklinov'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: zenklinov
email: abhishek@nagekar.com
linkedin_username: zenklinov
instagram_username: zenklinov

# absolute or relative
profile_picture: assets/images/head_circle.png
