title: Amanatullah Pandu Zenklinov
description: Data Scientist & Lecturer
site_title: '@zenklinov - Amanatullah Pandu Zenklinov'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: zenklinov
email: apzenklinov@gmail.com
linkedin_username: zenklinov
instagram_username: zenklinov

# absolute or relative
profile_picture: assets/images/foto1.png
